name: PlatformIO Build for Nucleo F030R8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example:
          - examples/01_LED_Blink

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python (required for PlatformIO)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Install PlatformIO Core
      - name: Install PlatformIO
        run: |
          python3 -m pip install --upgrade pip
          pip install platformio

      # Step 4: Build the PlatformIO project for Nucleo F030R8
      - name: Build PlatformIO project
        working-directory: ${{ matrix.example }}
        run: |
          platformio run --environment nucleo_f030r8
